### ISSUE TITLE
Allow direct HTML input

### ISSUE THREAD

**Issue by fisker** [sindresorhus/capture-website-cli#13]
https://github.com/sindresorhus/capture-website/issues/3 

https://github.com/sindresorhus/capture-website/pull/33

**Comment by fisker** [comment]
Before I start, there is something I want cofirm,

If we add the same flag `--input-type` as `capture-website` will ask people use like

```bash
capture-website "<h1>awsome</h1>" screenshot.png --input-type html
```

I this might not easy to use

I suggest we use `--html` boolean flag, this will be easier to user

```bash
capture-website "<h1>awsome</h1>" screenshot.png --html
```

And we should support probably `stdin`, so we can 

```bash
curl https://www.google.com | capture-website screenshot.png --html
cat my.html | capture-website --html > screenshot.png
```

**Comment by sindresorhus** [comment]
Agreed to both.

https://github.com/sindresorhus/capture-website/releases/tag/v0.5.0

**Comment by fisker** [comment]
There might be confusion to support `stdin`

```bash
cat myfile | capture-website screenshot.png --html
```

1. capture-website string `screenshot.png` and output to `stdout`
2. capture-website string from `myfile` and output to `screenshot.png`

It's not clear

**Comment by sindresorhus** [comment]
Let's change it to a `--output` flag for all uses. I don't think we need a `--html` flag. We just make stdin be the only way to input raw HTML.

So this will be how you use it:

```
echo '<h1>dad</h1>' | capture-website --output=screenshot.png
capture-website myfile.html --output=screenshot.png
```

**Comment by fisker** [comment]
OK
