### ISSUE TITLE
OpenGL pages not captured with high cpu usage and never ending

### ISSUE THREAD

**Issue by jordiblanchcarles** [sindresorhus/capture-website-cli#15]
Hello!

I've trying capture-website-cli and it works for most websites I've tried, but when trying to capture an OpenGL website like https://webglsamples.org/aquarium/aquarium.html, I'm getting a very high cpu usage and the process is never ending, also using the --timeout flag.

I'm using Linux Ubuntu 16.04 on a x64 CPU.

Do you figure out how to solve this problem?

Thank you!

**Comment by sindresorhus** [comment]
This is most likely an issue with https://github.com/GoogleChrome/puppeteer
