### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by jaymin009** [sindresorhus/capture-website-cli#25]
Hello @sindresorhus @fisker @hicom150 @dirathea @olso 

I have installed capture-website-cli on AWS server. if i will try to run with command:

> capture-website --help
it will showing some internal library error. attached screen shot. Kindly help me to solve this issue.
![Screenshot 2020-11-13 at 5 42 52 PM](https://user-images.githubusercontent.com/6341817/99071232-b7655580-25d7-11eb-9cb2-35fc2a950317.png)

 TIA.

**Comment by sindresorhus** [comment]
I think it's clear from the error stack that the error is not coming from `capture-website`, so this is not really the place to open this issue.

The issue is that you need a newer Node.js version.
