### ISSUE TITLE
height capped?

### ISSUE THREAD

**Issue by voidnothings** [sindresorhus/capture-website-cli#26]
- trying to capture a page with an estimate height of 7xxx px, using the following options --width=1440 --height=7000 --full-page --scale-factor=2
- checking the output file the remaining space at the bottom beyond 4xxxpx+ looks weird, it's as if the process gets repeated and the same page header is appended at the bottom? https://i.imgur.com/Yeko0Dz.png same page at --height=4000 https://i.imgur.com/SphUVlZ.png

**Comment by sindresorhus** [comment]
The `--full-page` option is a bit broken at the moment: https://github.com/sindresorhus/capture-website/issues/58

This might also be related to: https://github.com/sindresorhus/capture-website/issues/59

**Comment by voidnothings** [comment]
oh, cool thanks!
