### ISSUE TITLE
`--style="red.css"` does not work

### ISSUE THREAD

**Issue by BananaAcid** [sindresorhus/capture-website-cli#29]
Style file will not be included?

using the command

```ps1
. .\node_modules\.bin\capture-website.ps1 https://appjigger.com --output=appjigger.com.jpeg --full-page --style="red.css" --overwrite

```

red.css:
```
* {
  background: red !important;
}
```

**Comment by sindresorhus** [comment]
Works fine for me with the latest `capture-website-cli` version:

![appjigger com](https://user-images.githubusercontent.com/170270/104008840-99356380-51dc-11eb-9bde-da5bc2d63118.jpeg)

**Comment by BananaAcid** [comment]
... for me too :)

On windows, I got a BOM in the file - I guess that broke it. Removing the BOM and the UTF-16 Marker, it seemed to work.
