### ISSUE TITLE
TypeError: options.removeElements.map is not a function

### ISSUE THREAD

**Issue by leifniem** [sindresorhus/capture-website-cli#3]
The error in exact terms was:
`TypeError: options.removeElements.map is not a function
    at captureWebsite (/Volumes/Files/Users/leif/.config/yarn/global/node_modules/capture-website/index.js:137:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

with the command being:
`capture-website --emulate-device="iPhone X" --remove-elements=".cookie-dialog" https://erlensee-aktuell.com ea.jpg`

Same occurrence for --hide-elements with matching names.

Thanks for all your great work!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/capture-website-cli/releases/tag/v0.1.2 :)

**Comment by leifniem** [comment]
Thanks :)
