### ISSUE TITLE
Partially hot: tot able to use it in github workflows

### ISSUE THREAD

**Issue by aborruso** [sindresorhus/capture-website-cli#31]
Hi,
I have this very basic script

```bash
folder="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$folder"/rawdata
mkdir -p "$folder"/processing

npm list -g --depth=0

rm "$folder"/rawdata/"$reg".png
capture-website --delay 5 --full-page --width 1280 --height  720 --output  "$folder"/rawdata/"$reg".png "https://ondata.github.io/vaccinipertutti/?area=SIC"
```

I run it using this github workflow (it's Ubuntu 20.04.2 LTS), in which I set capture-website-cli installation in this way

```
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
NPM_CONFIG_PREFIX=~/.npm-global
npm install -g capture-website
```

But when the script runs I have this error:

```
./test.sh: line 13: capture-website: command not found
```

It seems that it has been not installed in `~/.npm-global`.
If I run  `find /home/runner -executable -name capture-website` I have

    /home/runner/.npm-global/lib/node_modules/capture-website

Do you have some advice to solve my problem?

Thank you

**Comment by sindresorhus** [comment]
I would try asking in https://github.community/c/software-development/47 Your question is about `npm`, not specifically this package.
