### ISSUE TITLE
Outputing the image in the cli

### ISSUE THREAD

**Issue by MattixNow** [sindresorhus/capture-website-cli#4]
If user don't provide option, the app log the outputed screenshot.
![2019-02-19 23_03_41-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/32040951/53050877-a20ed600-349a-11e9-8788-d07693c79ea7.png)

**Comment by sindresorhus** [comment]
That's by design. From `capture-website --help`:

> The screenshot will be written to stdout if there's no output file argument

This is useful so you can pipe it somewhere else without touching the filesystem.
