### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by devinmcmanus** [sindresorhus/capture-website-cli#47]
Hi there,
I installed this package with `sudo npm install --global capture-website-cli ` and getting the following error when running `capture-website --help`:

```
file:///usr/local/lib/node_modules/capture-website-cli/cli.js:295
await main();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

I'm running this on Debian 11 under WSL 2 in Windows 10 using node 12.22.12 and npm 7.5.2.

Thanks!
Devin

**Comment by sindresorhus** [comment]
You need a newer Node.js version.
