### ISSUE TITLE
Multiple filenames

### ISSUE THREAD

**Issue by bendada3** [sindresorhus/capture-website-cli#8]
Hello,
Is there way to set multiple output filenames in one instance of pageres?

Someting like this:

pageres [ http://google.com --filename='goo' ]  [ http://facebook.com --filename='face' ]

**Comment by sindresorhus** [comment]
I think you opened this on the wrong repo.

**Comment by bendada3** [comment]
I use bash CLI so I think it is right place

**Comment by sindresorhus** [comment]
You're asking about Pageres, but this is not the Pageres repo.

**Comment by bendada3** [comment]
damn I am so blind, sorry :/
