### ISSUE TITLE
Incorrect documentation for executable in docker

### ISSUE THREAD

**Issue by AlmogCohen** [sindresorhus/capture-website-cli#9]
When installed into docker, the package name is `webcapture` and not `website-capture` as stated in the main readme.

**Comment by sindresorhus** [comment]
That is incorrect: https://github.com/sindresorhus/capture-website-cli/blob/f041897098b0af8421b36e008238934319a87e42/package.json#L12-L14

You probably have some other tool installed or something else.

**Comment by AlmogCohen** [comment]
I checked again and what I've wrote is correct :) I just confirmed with Docker installation with this npm package installed alone.

I figured out that the issue could stem from the fact that the version on `npm` is `0.1.0` and not 0.2.0 as I can see released on this repo. 

Please fix :)

**Comment by AlmogCohen** [comment]
Yes, I can confirm that this is indeed an issue with the outdated package in npm.

After installing the latest release with `npm install https://github.com/sindresorhus/capture-website-cli.git#f041897098b0af8421b36e008238934319a87e42` the issue was solved
